name: flutter_4_7_1_jp_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  customizable_counter: ^1.0.4
  flutter:
    sdk: flutter
  flutter_sficon: ^1.1.2
  flutter_svg: ^2.0.10+1
  toggle_switch: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
   - assets/details/
   - assets/grafiken/
   - assets/background/
   - assets/